### PR TITLE
Add suffix tag to Genesect

### PR DESCRIPTION
**Pull request by BartmanEH**

### CODE REVIEW

**Comment by Rplus** [comment]
PS:
I'm not sure this is a good idea or not to use emoji for them:
🔥 ⚡ ❄️ 💧

**Comment by BartmanEH** [comment]
I'm struggling with GitHub; nomenclature, how it works, etc. In my "branch" for adding Genesect, every Genesect already has a unique "type" field. Did I put that in there already? Or did you add it somehow into my branch? Either way, I don't know how to change it or incorporate it into 'this' pull request--I usually cancel a pull request and create a new one with my new commits.

Anyway, I agree we can use emoji suffix if you like. Do I need to make type additions and emoji change and make a new pull request?

**Comment by Rplus** [comment]
You could edit them on github PR page directly
image

**Comment by Rplus** [comment]
> OK, but what's the difference between "type" and "isotope"?
That just works for old image folder.
you could use one of them you like for new naming system before I refactor.

**Pull request merged**
