### PR TITLE
add Grubbin family and add Genesect tags

### PR DESCRIPTION
**Pull request by BartmanEH**

### CODE REVIEW

**Review by Rplus — CHANGES_REQUESTED** [review]
there are wrong json format in your update

**Comment by Rplus** [comment]
image
need to follow JSON format

line 5395: leak a trailing comma

image

In normal case, 
I recommend to don't add newline as the final line of a json object.
There will be two line change, not good for reviewing.

**Comment by Rplus** [comment]
And I suggest try to use git branch to send PR.
That will help you separate different changes.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

1. on master branch, type `git checkout -b new-branch-name-you-like` to create an new branch based on current master branch.
2. just update the file, and push after commit them
3. go to GitHub repo page to send a new PR with the new branch

**Comment by BartmanEH** [comment]
> In normal case, I recommend to don't add newline as the final line of a json object. There will be two line change, not good for reviewing.

What is a better 'best practice'? To delete the whole block and add new block with the new line? or just add the newline in the middle of the block, not at the end?

**Comment by BartmanEH** [comment]
> And I suggest try to use git branch to send PR. That will help you separate different changes.
Ah yes, I forgot. I did that for previous changes but forgot the workflow already :-) 

> 1. on master branch, type `git checkout -b new-branch-name-you-like` to create an new branch based on current master branch.
> 2. just update the file, and push after commit them
> 3. go to GitHub repo page to send a new PR with the new branch
I have found command line github way too complicated for me so I don't fork/clone the repo into my system terminal--I'm using the github web interface which is also not great for beginners but a bit more manageable for me.

**Comment by BartmanEH** [comment]
ok, i'm redoing this PR and two separate PRs

**Comment by Rplus** [comment]
> > In normal case, I recommend to don't add newline as the final line of a json object. There will be two line change, not good for reviewing.
> 
> What is a better 'best practice'? To delete the whole block and add new block with the new line? or just add the newline in the middle of the block, not at the end?

I think there is no `best practice` for everyone.
`Avoid to add new content after the final line`
That will reduce diff area, good to review (maybe just) for me :).
For other developers, maybe it is not a good idea to mess the json property order.

I'm lazy, so I just add new content before final line.
just like this:
https://github.com/Rplus/Pokemon-shiny/commit/b20ae71fc3e83c802b02b8d73053e726e72bc0c4

**Pull request closed without merging**
